BEGIN;

INSERT INTO country VALUES ('AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', 4);
INSERT INTO country VALUES ('AX', 'ALAND ISLANDS', 'Åland Islands', 'ALA', 248);
INSERT INTO country VALUES ('AL', 'ALBANIA', 'Albania', 'ALB', 8);
INSERT INTO country VALUES ('DZ', 'ALGERIA', 'Algeria', 'DZA', 12);
INSERT INTO country VALUES ('AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', 16);
INSERT INTO country VALUES ('AD', 'ANDORRA', 'Andorra', 'AND', 20);
INSERT INTO country VALUES ('AO', 'ANGOLA', 'Angola', 'AGO', 24);
INSERT INTO country VALUES ('AI', 'ANGUILLA', 'Anguilla', 'AIA', 660);
INSERT INTO country VALUES ('AQ', 'ANTARCTICA', 'Antarctica', 'ATA', 10);
INSERT INTO country VALUES ('AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', 28);
INSERT INTO country VALUES ('AR', 'ARGENTINA', 'Argentina', 'ARG', 32);
INSERT INTO country VALUES ('AM', 'ARMENIA', 'Armenia', 'ARM', 51);
INSERT INTO country VALUES ('AW', 'ARUBA', 'Aruba', 'ABW', 533);
INSERT INTO country VALUES ('AU', 'AUSTRALIA', 'Australia', 'AUS', 36);
INSERT INTO country VALUES ('AT', 'AUSTRIA', 'Austria', 'AUT', 40);
INSERT INTO country VALUES ('AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', 31);
INSERT INTO country VALUES ('BS', 'BAHAMAS', 'Bahamas', 'BHS', 44);
INSERT INTO country VALUES ('BH', 'BAHRAIN', 'Bahrain', 'BHR', 48);
INSERT INTO country VALUES ('BD', 'BANGLADESH', 'Bangladesh', 'BGD', 50);
INSERT INTO country VALUES ('BB', 'BARBADOS', 'Barbados', 'BRB', 52);
INSERT INTO country VALUES ('BY', 'BELARUS', 'Belarus', 'BLR', 112);
INSERT INTO country VALUES ('BE', 'BELGIUM', 'Belgium', 'BEL', 56);
INSERT INTO country VALUES ('BZ', 'BELIZE', 'Belize', 'BLZ', 84);
INSERT INTO country VALUES ('BJ', 'BENIN', 'Benin', 'BEN', 204);
INSERT INTO country VALUES ('BM', 'BERMUDA', 'Bermuda', 'BMU', 60);
INSERT INTO country VALUES ('BT', 'BHUTAN', 'Bhutan', 'BTN', 64);
INSERT INTO country VALUES ('BO', 'BOLIVIA', 'Bolivia', 'BOL', 68);
INSERT INTO country VALUES ('BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', 70);
INSERT INTO country VALUES ('BW', 'BOTSWANA', 'Botswana', 'BWA', 72);
INSERT INTO country VALUES ('BV', 'BOUVET ISLAND', 'Bouvet Island', 'BVT', 74);
INSERT INTO country VALUES ('BR', 'BRAZIL', 'Brazil', 'BRA', 76);
INSERT INTO country VALUES ('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', 'IOT', 86);
INSERT INTO country VALUES ('BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', 96);
INSERT INTO country VALUES ('BG', 'BULGARIA', 'Bulgaria', 'BGR', 100);
INSERT INTO country VALUES ('BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', 854);
INSERT INTO country VALUES ('BI', 'BURUNDI', 'Burundi', 'BDI', 108);
INSERT INTO country VALUES ('KH', 'CAMBODIA', 'Cambodia', 'KHM', 116);
INSERT INTO country VALUES ('CM', 'CAMEROON', 'Cameroon', 'CMR', 120);
INSERT INTO country VALUES ('CA', 'CANADA', 'Canada', 'CAN', 124);
INSERT INTO country VALUES ('CV', 'CAPE VERDE', 'Cape Verde', 'CPV', 132);
INSERT INTO country VALUES ('KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', 136);
INSERT INTO country VALUES ('CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', 140);
INSERT INTO country VALUES ('TD', 'CHAD', 'Chad', 'TCD', 148);
INSERT INTO country VALUES ('CL', 'CHILE', 'Chile', 'CHL', 152);
INSERT INTO country VALUES ('CN', 'CHINA', 'China', 'CHN', 156);
INSERT INTO country VALUES ('CX', 'CHRISTMAS ISLAND', 'Christmas Island', 'CXR', 162);
INSERT INTO country VALUES ('CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', 'CCK', 166);
INSERT INTO country VALUES ('CO', 'COLOMBIA', 'Colombia', 'COL', 170);
INSERT INTO country VALUES ('KM', 'COMOROS', 'Comoros', 'COM', 174);
INSERT INTO country VALUES ('CG', 'CONGO', 'Congo', 'COG', 178);
INSERT INTO country VALUES ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Democratic Republic of the Congo', 'COD', 180);
INSERT INTO country VALUES ('CK', 'COOK ISLANDS', 'Cook Islands', 'COK', 184);
INSERT INTO country VALUES ('CR', 'COSTA RICA', 'Costa Rica', 'CRI', 188);
INSERT INTO country VALUES ('CI', 'COTE D''IVOIRE', 'Côte d''Ivoire', 'CIV', 384);
INSERT INTO country VALUES ('HR', 'CROATIA', 'Croatia', 'HRV', 191);
INSERT INTO country VALUES ('CU', 'CUBA', 'Cuba', 'CUB', 192);
INSERT INTO country VALUES ('CY', 'CYPRUS', 'Cyprus', 'CYP', 196);
INSERT INTO country VALUES ('CZ', 'CZECH REPUBLIC', 'Czech Republic', 'CZE', 203);
INSERT INTO country VALUES ('DK', 'DENMARK', 'Denmark', 'DNK', 208);
INSERT INTO country VALUES ('DJ', 'DJIBOUTI', 'Djibouti', 'DJI', 262);
INSERT INTO country VALUES ('DM', 'DOMINICA', 'Dominica', 'DMA', 212);
INSERT INTO country VALUES ('DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', 214);
INSERT INTO country VALUES ('EC', 'ECUADOR', 'Ecuador', 'ECU', 218);
INSERT INTO country VALUES ('EG', 'EGYPT', 'Egypt', 'EGY', 818);
INSERT INTO country VALUES ('SV', 'EL SALVADOR', 'El Salvador', 'SLV', 222);
INSERT INTO country VALUES ('GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', 226);
INSERT INTO country VALUES ('ER', 'ERITREA', 'Eritrea', 'ERI', 232);
INSERT INTO country VALUES ('EE', 'ESTONIA', 'Estonia', 'EST', 233);
INSERT INTO country VALUES ('ET', 'ETHIOPIA', 'Ethiopia', 'ETH', 231);
INSERT INTO country VALUES ('FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', 238);
INSERT INTO country VALUES ('FO', 'FAROE ISLANDS', 'Faeroe Islands', 'FRO', 234);
INSERT INTO country VALUES ('FJ', 'FIJI', 'Fiji', 'FJI', 242);
INSERT INTO country VALUES ('FI', 'FINLAND', 'Finland', 'FIN', 246);
INSERT INTO country VALUES ('FR', 'FRANCE', 'France', 'FRA', 250);
INSERT INTO country VALUES ('GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', 254);
INSERT INTO country VALUES ('PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', 258);
INSERT INTO country VALUES ('TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', 'ATF', 260);
INSERT INTO country VALUES ('GA', 'GABON', 'Gabon', 'GAB', 266);
INSERT INTO country VALUES ('GM', 'GAMBIA', 'Gambia', 'GMB', 270);
INSERT INTO country VALUES ('GE', 'GEORGIA', 'Georgia', 'GEO', 268);
INSERT INTO country VALUES ('DE', 'GERMANY', 'Germany', 'DEU', 276);
INSERT INTO country VALUES ('GH', 'GHANA', 'Ghana', 'GHA', 288);
INSERT INTO country VALUES ('GI', 'GIBRALTAR', 'Gibraltar', 'GIB', 292);
INSERT INTO country VALUES ('GR', 'GREECE', 'Greece', 'GRC', 300);
INSERT INTO country VALUES ('GL', 'GREENLAND', 'Greenland', 'GRL', 304);
INSERT INTO country VALUES ('GD', 'GRENADA', 'Grenada', 'GRD', 308);
INSERT INTO country VALUES ('GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', 312);
INSERT INTO country VALUES ('GU', 'GUAM', 'Guam', 'GUM', 316);
INSERT INTO country VALUES ('GT', 'GUATEMALA', 'Guatemala', 'GTM', 320);
INSERT INTO country VALUES ('GG', 'GUERNSEY', 'Guernsey', 'GGY', 831);
INSERT INTO country VALUES ('GN', 'GUINEA', 'Guinea', 'GIN', 324);
INSERT INTO country VALUES ('GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', 624);
INSERT INTO country VALUES ('GY', 'GUYANA', 'Guyana', 'GUY', 328);
INSERT INTO country VALUES ('HT', 'HAITI', 'Haiti', 'HTI', 332);
INSERT INTO country VALUES ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', 'HMD', 334);
INSERT INTO country VALUES ('VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See', 'VAT', 336);
INSERT INTO country VALUES ('HN', 'HONDURAS', 'Honduras', 'HND', 340);
INSERT INTO country VALUES ('HK', 'HONG KONG', 'Hong Kong Special Administrative Region of China', 'HKG', 344);
INSERT INTO country VALUES ('HU', 'HUNGARY', 'Hungary', 'HUN', 348);
INSERT INTO country VALUES ('IS', 'ICELAND', 'Iceland', 'ISL', 352);
INSERT INTO country VALUES ('IN', 'INDIA', 'India', 'IND', 356);
INSERT INTO country VALUES ('ID', 'INDONESIA', 'Indonesia', 'IDN', 360);
INSERT INTO country VALUES ('IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', 364);
INSERT INTO country VALUES ('IQ', 'IRAQ', 'Iraq', 'IRQ', 368);
INSERT INTO country VALUES ('IE', 'IRELAND', 'Ireland', 'IRL', 372);
INSERT INTO country VALUES ('IM', 'ISLE OF MAN', 'Isle of Man', 'IMN', 833);
INSERT INTO country VALUES ('IL', 'ISRAEL', 'Israel', 'ISR', 376);
INSERT INTO country VALUES ('IT', 'ITALY', 'Italy', 'ITA', 380);
INSERT INTO country VALUES ('JM', 'JAMAICA', 'Jamaica', 'JAM', 388);
INSERT INTO country VALUES ('JP', 'JAPAN', 'Japan', 'JPN', 392);
INSERT INTO country VALUES ('JE', 'JERSEY', 'Jersey', 'JEY', 832);
INSERT INTO country VALUES ('JO', 'JORDAN', 'Jordan', 'JOR', 400);
INSERT INTO country VALUES ('KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', 398);
INSERT INTO country VALUES ('KE', 'KENYA', 'Kenya', 'KEN', 404);
INSERT INTO country VALUES ('KI', 'KIRIBATI', 'Kiribati', 'KIR', 296);
INSERT INTO country VALUES ('KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'Democratic People''s Republic of Korea', 'PRK', 408);
INSERT INTO country VALUES ('KR', 'KOREA, REPUBLIC OF', 'Republic of Korea', 'KOR', 410);
INSERT INTO country VALUES ('KW', 'KUWAIT', 'Kuwait', 'KWT', 414);
INSERT INTO country VALUES ('KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', 417);
INSERT INTO country VALUES ('LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'Lao People''s Democratic Republic', 'LAO', 418);
INSERT INTO country VALUES ('LV', 'LATVIA', 'Latvia', 'LVA', 428);
INSERT INTO country VALUES ('LB', 'LEBANON', 'Lebanon', 'LBN', 422);
INSERT INTO country VALUES ('LS', 'LESOTHO', 'Lesotho', 'LSO', 426);
INSERT INTO country VALUES ('LR', 'LIBERIA', 'Liberia', 'LBR', 430);
INSERT INTO country VALUES ('LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', 434);
INSERT INTO country VALUES ('LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', 438);
INSERT INTO country VALUES ('LT', 'LITHUANIA', 'Lithuania', 'LTU', 440);
INSERT INTO country VALUES ('LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', 442);
INSERT INTO country VALUES ('MO', 'MACAO', 'Macao Special Administrative Region of China', 'MAC', 446);
INSERT INTO country VALUES ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'The former Yugoslav Republic of Macedonia', 'MKD', 807);
INSERT INTO country VALUES ('MG', 'MADAGASCAR', 'Madagascar', 'MDG', 450);
INSERT INTO country VALUES ('MW', 'MALAWI', 'Malawi', 'MWI', 454);
INSERT INTO country VALUES ('MY', 'MALAYSIA', 'Malaysia', 'MYS', 458);
INSERT INTO country VALUES ('MV', 'MALDIVES', 'Maldives', 'MDV', 462);
INSERT INTO country VALUES ('ML', 'MALI', 'Mali', 'MLI', 466);
INSERT INTO country VALUES ('MT', 'MALTA', 'Malta', 'MLT', 470);
INSERT INTO country VALUES ('MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', 584);
INSERT INTO country VALUES ('MQ', 'MARTINIQUE', 'Martinique', 'MTQ', 474);
INSERT INTO country VALUES ('MR', 'MAURITANIA', 'Mauritania', 'MRT', 478);
INSERT INTO country VALUES ('MU', 'MAURITIUS', 'Mauritius', 'MUS', 480);
INSERT INTO country VALUES ('YT', 'MAYOTTE', 'Mayotte', 'MYT', 175);
INSERT INTO country VALUES ('MX', 'MEXICO', 'Mexico', 'MEX', 484);
INSERT INTO country VALUES ('FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', 583);
INSERT INTO country VALUES ('MD', 'MOLDOVA, REPUBLIC OF', 'Republic of Moldova', 'MDA', 498);
INSERT INTO country VALUES ('MC', 'MONACO', 'Monaco', 'MCO', 492);
INSERT INTO country VALUES ('MN', 'MONGOLIA', 'Mongolia', 'MNG', 496);
INSERT INTO country VALUES ('ME', 'MONTENEGRO', 'Montenegro', 'MNE', 499);
INSERT INTO country VALUES ('MS', 'MONTSERRAT', 'Montserrat', 'MSR', 500);
INSERT INTO country VALUES ('MA', 'MOROCCO', 'Morocco', 'MAR', 504);
INSERT INTO country VALUES ('MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', 508);
INSERT INTO country VALUES ('MM', 'MYANMAR', 'Myanmar', 'MMR', 104);
INSERT INTO country VALUES ('NA', 'NAMIBIA', 'Namibia', 'NAM', 516);
INSERT INTO country VALUES ('NR', 'NAURU', 'Nauru', 'NRU', 520);
INSERT INTO country VALUES ('NP', 'NEPAL', 'Nepal', 'NPL', 524);
INSERT INTO country VALUES ('NL', 'NETHERLANDS', 'Netherlands', 'NLD', 528);
INSERT INTO country VALUES ('AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'ANT', 530);
INSERT INTO country VALUES ('NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', 540);
INSERT INTO country VALUES ('NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', 554);
INSERT INTO country VALUES ('NI', 'NICARAGUA', 'Nicaragua', 'NIC', 558);
INSERT INTO country VALUES ('NE', 'NIGER', 'Niger', 'NER', 562);
INSERT INTO country VALUES ('NG', 'NIGERIA', 'Nigeria', 'NGA', 566);
INSERT INTO country VALUES ('NU', 'NIUE', 'Niue', 'NIU', 570);
INSERT INTO country VALUES ('NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', 574);
INSERT INTO country VALUES ('MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', 580);
INSERT INTO country VALUES ('NO', 'NORWAY', 'Norway', 'NOR', 578);
INSERT INTO country VALUES ('OM', 'OMAN', 'Oman', 'OMN', 512);
INSERT INTO country VALUES ('PK', 'PAKISTAN', 'Pakistan', 'PAK', 586);
INSERT INTO country VALUES ('PW', 'PALAU', 'Palau', 'PLW', 585);
INSERT INTO country VALUES ('PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Occupied Palestinian Territory', 'PSE', 275);
INSERT INTO country VALUES ('PA', 'PANAMA', 'Panama', 'PAN', 591);
INSERT INTO country VALUES ('PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', 598);
INSERT INTO country VALUES ('PY', 'PARAGUAY', 'Paraguay', 'PRY', 600);
INSERT INTO country VALUES ('PE', 'PERU', 'Peru', 'PER', 604);
INSERT INTO country VALUES ('PH', 'PHILIPPINES', 'Philippines', 'PHL', 608);
INSERT INTO country VALUES ('PN', 'PITCAIRN', 'Pitcairn', 'PCN', 612);
INSERT INTO country VALUES ('PL', 'POLAND', 'Poland', 'POL', 616);
INSERT INTO country VALUES ('PT', 'PORTUGAL', 'Portugal', 'PRT', 620);
INSERT INTO country VALUES ('PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', 630);
INSERT INTO country VALUES ('QA', 'QATAR', 'Qatar', 'QAT', 634);
INSERT INTO country VALUES ('RE', 'REUNION', 'Réunion', 'REU', 638);
INSERT INTO country VALUES ('RO', 'ROMANIA', 'Romania', 'ROU', 642);
INSERT INTO country VALUES ('RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', 643);
INSERT INTO country VALUES ('RW', 'RWANDA', 'Rwanda', 'RWA', 646);
INSERT INTO country VALUES ('SH', 'SAINT HELENA', 'Saint Helena', 'SHN', 654);
INSERT INTO country VALUES ('KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', 659);
INSERT INTO country VALUES ('LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', 662);
INSERT INTO country VALUES ('PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', 666);
INSERT INTO country VALUES ('VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', 670);
INSERT INTO country VALUES ('WS', 'SAMOA', 'Samoa', 'WSM', 882);
INSERT INTO country VALUES ('SM', 'SAN MARINO', 'San Marino', 'SMR', 674);
INSERT INTO country VALUES ('ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', 678);
INSERT INTO country VALUES ('SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', 682);
INSERT INTO country VALUES ('SN', 'SENEGAL', 'Senegal', 'SEN', 686);
INSERT INTO country VALUES ('RS', 'SERBIA', 'Serbia', 'SRB', 688);
INSERT INTO country VALUES ('SC', 'SEYCHELLES', 'Seychelles', 'SYC', 690);
INSERT INTO country VALUES ('SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', 694);
INSERT INTO country VALUES ('SG', 'SINGAPORE', 'Singapore', 'SGP', 702);
INSERT INTO country VALUES ('SK', 'SLOVAKIA', 'Slovakia', 'SVK', 703);
INSERT INTO country VALUES ('SI', 'SLOVENIA', 'Slovenia', 'SVN', 705);
INSERT INTO country VALUES ('SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', 90);
INSERT INTO country VALUES ('SO', 'SOMALIA', 'Somalia', 'SOM', 706);
INSERT INTO country VALUES ('ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', 710);
INSERT INTO country VALUES ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', 'SGS', 239);
INSERT INTO country VALUES ('ES', 'SPAIN', 'Spain', 'ESP', 724);
INSERT INTO country VALUES ('LK', 'SRI LANKA', 'Sri Lanka', 'LKA', 144);
INSERT INTO country VALUES ('SD', 'SUDAN', 'Sudan', 'SDN', 736);
INSERT INTO country VALUES ('SR', 'SURINAME', 'Suriname', 'SUR', 740);
INSERT INTO country VALUES ('SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen Islands', 'SJM', 744);
INSERT INTO country VALUES ('SZ', 'SWAZILAND', 'Swaziland', 'SWZ', 748);
INSERT INTO country VALUES ('SE', 'SWEDEN', 'Sweden', 'SWE', 752);
INSERT INTO country VALUES ('CH', 'SWITZERLAND', 'Switzerland', 'CHE', 756);
INSERT INTO country VALUES ('SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', 760);
INSERT INTO country VALUES ('TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', 158);
INSERT INTO country VALUES ('TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', 762);
INSERT INTO country VALUES ('TZ', 'TANZANIA, UNITED REPUBLIC OF', 'United Republic of Tanzania', 'TZA', 834);
INSERT INTO country VALUES ('TH', 'THAILAND', 'Thailand', 'THA', 764);
INSERT INTO country VALUES ('TL', 'TIMOR-LESTE', 'Timor-Leste', 'TLS', 626);
INSERT INTO country VALUES ('TG', 'TOGO', 'Togo', 'TGO', 768);
INSERT INTO country VALUES ('TK', 'TOKELAU', 'Tokelau', 'TKL', 772);
INSERT INTO country VALUES ('TO', 'TONGA', 'Tonga', 'TON', 776);
INSERT INTO country VALUES ('TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', 780);
INSERT INTO country VALUES ('TN', 'TUNISIA', 'Tunisia', 'TUN', 788);
INSERT INTO country VALUES ('TR', 'TURKEY', 'Turkey', 'TUR', 792);
INSERT INTO country VALUES ('TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', 795);
INSERT INTO country VALUES ('TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', 796);
INSERT INTO country VALUES ('TV', 'TUVALU', 'Tuvalu', 'TUV', 798);
INSERT INTO country VALUES ('UG', 'UGANDA', 'Uganda', 'UGA', 800);
INSERT INTO country VALUES ('UA', 'UKRAINE', 'Ukraine', 'UKR', 804);
INSERT INTO country VALUES ('AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', 784);
INSERT INTO country VALUES ('GB', 'UNITED KINGDOM', 'United Kingdom of Great Britain and Northern Ireland', 'GBR', 826);
INSERT INTO country VALUES ('US', 'UNITED STATES', 'United States of America', 'USA', 840);
INSERT INTO country VALUES ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', 'UMI', 581);
INSERT INTO country VALUES ('UY', 'URUGUAY', 'Uruguay', 'URY', 858);
INSERT INTO country VALUES ('UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', 860);
INSERT INTO country VALUES ('VU', 'VANUATU', 'Vanuatu', 'VUT', 548);
INSERT INTO country VALUES ('VE', 'VENEZUELA', 'Venezuela (Bolivarian Republic of)', 'VEN', 862);
INSERT INTO country VALUES ('VN', 'VIET NAM', 'Viet Nam', 'VNM', 704);
INSERT INTO country VALUES ('VG', 'VIRGIN ISLANDS, BRITISH', 'British Virgin Islands', 'VGB', 92);
INSERT INTO country VALUES ('VI', 'VIRGIN ISLANDS, U.S.', 'United States Virgin Islands', 'VIR', 850);
INSERT INTO country VALUES ('WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna Islands', 'WLF', 876);
INSERT INTO country VALUES ('EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', 732);
INSERT INTO country VALUES ('YE', 'YEMEN', 'Yemen', 'YEM', 887);
INSERT INTO country VALUES ('ZM', 'ZAMBIA', 'Zambia', 'ZMB', 894);
INSERT INTO country VALUES ('ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', 716);


--
-- Data for Name: country_calling_code; Type: TABLE DATA; Schema: public
--

INSERT INTO country_calling_code VALUES ('CN', '86');
INSERT INTO country_calling_code VALUES ('FR', '33');
INSERT INTO country_calling_code VALUES ('US', '1 ');


--
-- Data for Name: locale; Type: TABLE DATA; Schema: public
--

INSERT INTO locale VALUES ('zh-CN');
INSERT INTO locale VALUES ('fr-FR');
INSERT INTO locale VALUES ('en-US');

--
-- Data for Name: title; Type: TABLE DATA; Schema: public
--

INSERT INTO title VALUES ('先生', 'zh-CN');
INSERT INTO title VALUES ('女士', 'zh-CN');
INSERT INTO title VALUES ('Mr', 'en-US');
INSERT INTO title VALUES ('Mrs', 'en-US');
INSERT INTO title VALUES ('Miss', 'en-US');
INSERT INTO title VALUES ('Ms', 'en-US');

--
-- Data for Name: province; Type: TABLE DATA; Schema: public
--

INSERT INTO province VALUES ('AL', 'Alabama', 'US');
INSERT INTO province VALUES ('AK', 'Alaska', 'US');
INSERT INTO province VALUES ('AS', 'American Samoa', 'US');
INSERT INTO province VALUES ('AZ', 'Arizona', 'US');
INSERT INTO province VALUES ('AR', 'Arkansas', 'US');
INSERT INTO province VALUES ('CA', 'California', 'US');
INSERT INTO province VALUES ('CO', 'Colorado', 'US');
INSERT INTO province VALUES ('CT', 'Connecticut', 'US');
INSERT INTO province VALUES ('DE', 'Delaware', 'US');
INSERT INTO province VALUES ('DC', 'District of Columbia', 'US');
INSERT INTO province VALUES ('FM', 'Federated States of Micronesia', 'US');
INSERT INTO province VALUES ('FL', 'Florida', 'US');
INSERT INTO province VALUES ('GA', 'Georgia', 'US');
INSERT INTO province VALUES ('GU', 'Guam', 'US');
INSERT INTO province VALUES ('HI', 'Hawaii', 'US');
INSERT INTO province VALUES ('ID', 'Idaho', 'US');
INSERT INTO province VALUES ('IL', 'Illinois', 'US');
INSERT INTO province VALUES ('IN', 'Indiana', 'US');
INSERT INTO province VALUES ('IA', 'Iowa', 'US');
INSERT INTO province VALUES ('KS', 'Kansas', 'US');
INSERT INTO province VALUES ('KY', 'Kentucky', 'US');
INSERT INTO province VALUES ('LA', 'Louisiana', 'US');
INSERT INTO province VALUES ('ME', 'Maine', 'US');
INSERT INTO province VALUES ('MH', 'Marshall Islands', 'US');
INSERT INTO province VALUES ('MD', 'Maryland', 'US');
INSERT INTO province VALUES ('MA', 'Massachusetts', 'US');
INSERT INTO province VALUES ('MI', 'Michigan', 'US');
INSERT INTO province VALUES ('MN', 'Minnesota', 'US');
INSERT INTO province VALUES ('MS', 'Mississippi', 'US');
INSERT INTO province VALUES ('MO', 'Missouri', 'US');
INSERT INTO province VALUES ('MT', 'Montana', 'US');
INSERT INTO province VALUES ('NE', 'Nebraska', 'US');
INSERT INTO province VALUES ('NV', 'Nevada', 'US');
INSERT INTO province VALUES ('NH', 'New Hampshire', 'US');
INSERT INTO province VALUES ('NJ', 'New Jersey', 'US');
INSERT INTO province VALUES ('NM', 'New Mexico', 'US');
INSERT INTO province VALUES ('NY', 'New York', 'US');
INSERT INTO province VALUES ('NC', 'North Carolina', 'US');
INSERT INTO province VALUES ('ND', 'North Dakota', 'US');
INSERT INTO province VALUES ('MP', 'Northern Mariana Islands', 'US');
INSERT INTO province VALUES ('OH', 'Ohio', 'US');
INSERT INTO province VALUES ('OK', 'Oklahoma', 'US');
INSERT INTO province VALUES ('OR', 'Oregon', 'US');
INSERT INTO province VALUES ('PW', 'Palau', 'US');
INSERT INTO province VALUES ('PA', 'Pennsylvania', 'US');
INSERT INTO province VALUES ('PR', 'Puerto Rico', 'US');
INSERT INTO province VALUES ('RI', 'Rhode Island', 'US');
INSERT INTO province VALUES ('SC', 'South Carolina', 'US');
INSERT INTO province VALUES ('SD', 'South Dakota', 'US');
INSERT INTO province VALUES ('TN', 'Tennessee', 'US');
INSERT INTO province VALUES ('TX', 'Texas', 'US');
INSERT INTO province VALUES ('UT', 'Utah', 'US');
INSERT INTO province VALUES ('VT', 'Vermont', 'US');
INSERT INTO province VALUES ('VI', 'Virgin Islands', 'US');
INSERT INTO province VALUES ('VA', 'Virginia', 'US');
INSERT INTO province VALUES ('WA', 'Washington', 'US');
INSERT INTO province VALUES ('WV', 'West Virginia', 'US');
INSERT INTO province VALUES ('WI', 'Wisconsin', 'US');
INSERT INTO province VALUES ('WY', 'Wyoming', 'US');
INSERT INTO province VALUES ('AB', 'Alberta', 'CA');
INSERT INTO province VALUES ('BC', 'British Columbia', 'CA');
INSERT INTO province VALUES ('MB', 'Manitoba', 'CA');
INSERT INTO province VALUES ('NB', 'New Brunswick', 'CA');
INSERT INTO province VALUES ('NL', 'Newfoundland and Labrador', 'CA');
INSERT INTO province VALUES ('NT', 'Northwest Territories', 'CA');
INSERT INTO province VALUES ('NS', 'Nova Scotia', 'CA');
INSERT INTO province VALUES ('NU', 'Nunavut', 'CA');
INSERT INTO province VALUES ('ON', 'Ontario', 'CA');
INSERT INTO province VALUES ('PE', 'Prince Edward Island', 'CA');
INSERT INTO province VALUES ('QC', 'Quebec', 'CA');
INSERT INTO province VALUES ('SK', 'Saskatchewan', 'CA');
INSERT INTO province VALUES ('YT', 'Yukon', 'CA');
INSERT INTO province VALUES ('BJ', '北京', 'CN');
INSERT INTO province VALUES ('TJ', '天津', 'CN');
INSERT INTO province VALUES ('HE', '河北', 'CN');
INSERT INTO province VALUES ('SX', '山西', 'CN');
INSERT INTO province VALUES ('NM', '内蒙古', 'CN');
INSERT INTO province VALUES ('LN', '辽宁', 'CN');
INSERT INTO province VALUES ('JL', '吉林', 'CN');
INSERT INTO province VALUES ('HL', '黑龙江', 'CN');
INSERT INTO province VALUES ('SH', '上海', 'CN');
INSERT INTO province VALUES ('JS', '江苏', 'CN');
INSERT INTO province VALUES ('ZJ', '浙江', 'CN');
INSERT INTO province VALUES ('AH', '安徽', 'CN');
INSERT INTO province VALUES ('FJ', '福建', 'CN');
INSERT INTO province VALUES ('JX', '江西', 'CN');
INSERT INTO province VALUES ('SD', '山东', 'CN');
INSERT INTO province VALUES ('HA', '河南', 'CN');
INSERT INTO province VALUES ('HB', '湖北', 'CN');
INSERT INTO province VALUES ('HN', '湖南', 'CN');
INSERT INTO province VALUES ('GD', '广东', 'CN');
INSERT INTO province VALUES ('GX', '广西', 'CN');
INSERT INTO province VALUES ('HI', '海南', 'CN');
INSERT INTO province VALUES ('CQ', '重庆', 'CN');
INSERT INTO province VALUES ('SC', '四川', 'CN');
INSERT INTO province VALUES ('GZ', '贵州', 'CN');
INSERT INTO province VALUES ('YN', '云南', 'CN');
INSERT INTO province VALUES ('XZ', '西藏', 'CN');
INSERT INTO province VALUES ('SN', '陕西', 'CN');
INSERT INTO province VALUES ('GS', '甘肃', 'CN');
INSERT INTO province VALUES ('QH', '青海', 'CN');
INSERT INTO province VALUES ('NX', '宁夏', 'CN');
INSERT INTO province VALUES ('XJ', '新疆', 'CN');
INSERT INTO province VALUES ('HK', '香港', 'CN');
INSERT INTO province VALUES ('MC', '澳门', 'CN');
INSERT INTO province VALUES ('TW', '台湾', 'CN');

COMMIT;
